url: https://www.enomosphere.net
title: ひよこっ!
description: 飛ばないハトはひよこも同然
theme: minima
exclude:
  - .gitignore
header_pages:
  - sqlite.md
paginate: 5
minima:
  date_format: "%Y-%m-%d"
  twitter: takeshi_enomoto
  github: tenomoto
show_excerpts: true